import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/layout/providers';
import { Toaster } from '@/components/ui/toaster';
import Header from '@/components/layout/header/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <Toaster />
          <div className="container mx-auto flex min-h-screen flex-col">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
